create outline of target_month search function view #406
hr-dash/hr-dash pull request #428
Opened 2017-01-24 14:42 UTC by masahiro-yamazaki

# 概要

# 再現・確認手順

# 対応Issue（任意）

# ToDo

- [ ] ラベル付け
- [ ] Assigneesで自分を選択

2017-01-25 10:56 UTC, ta-chibana commented on app/views/monthly_reports/index.html.slim
> +sass:
assets/stylesheets 配下のファイルに書くべきかなと思います！

2017-02-03 22:04 UTC, t-tonchim requested changes
@ta-chibana と同じくスタイルはassets/stylesheetsに別ファイルで書くべきかと思います。

2017-02-04 01:50 UTC, masahiro-yamazaki commented
@ta-chibana @tomoyuki-tanaka 
コメントありがとうございます！
今後はassets/stylesheetsにCSSを書きます！

2017-02-04 04:49 UTC, freezer530000 commented on app/models/monthly_report.rb
> +  def self.target_month_select_options
__[rubocop]__
* Method has too many lines. [11/10] [:ref](https://github.com/bbatsov/ruby-style-guide#short-methods)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-04 04:49 UTC, freezer530000 commented on app/models/monthly_report.rb
> +    target_months = self.all.pluck(:target_month).sort.uniq
__[rubocop]__
* Redundant `self` detected. [:ref](https://github.com/bbatsov/ruby-style-guide#no-self-unless-required)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-04 04:49 UTC, freezer530000 commented on app/controllers/monthly_reports_controller.rb
> +    @monthly_reports = @monthly_reports.where(target_month: search_params[:target_month].to_date) if search_params.try(:[],:target_month).present?
__[rubocop]__
* Space missing after comma. [:ref](https://github.com/bbatsov/ruby-style-guide#spaces-operators)
* Line is too long. [147/128] [:ref](https://github.com/bbatsov/ruby-style-guide#80-character-limits)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-04 04:49 UTC, freezer530000 commented
Click here if you want to create rubocop's auto-correct Pull Request
[![Auto Correct by SideCI](https://sideci.com/autofix.png)](https://sideci.com/gh/42654368/issues/pull_request/428/diff/f5fb9f3a461ebe19054fb2e376683880fb633f34?open_modal=1#rubocop)

See the documentation if you want to get more information about auto-correct.
[Document](https://sideci.com/ja/docs/autofix-rubocop)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-04 05:33 UTC, freezer530000 commented on app/models/monthly_report.rb
> +    target_months = self.released.pluck(:target_month).sort.uniq
__[rubocop]__
* Redundant `self` detected. [:ref](https://github.com/bbatsov/ruby-style-guide#no-self-unless-required)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-04 05:33 UTC, freezer530000 commented on app/models/monthly_report.rb
> +    first_month, last_month = target_months.first, target_months.last
__[rubocop]__
* Do not use parallel assignment. [:ref](https://github.com/bbatsov/ruby-style-guide#parallel-assignment, https://github.com/JuanitoFatas/fast-ruby#parallel-assignment-vs-sequential-assignment-code)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-04 05:33 UTC, freezer530000 commented
Click here if you want to create rubocop's auto-correct Pull Request
[![Auto Correct by SideCI](https://sideci.com/autofix.png)](https://sideci.com/gh/42654368/issues/pull_request/428/diff/fe47a8d545af37f82c283e80f7144dd8de2adaf7?open_modal=1#rubocop)

See the documentation if you want to get more information about auto-correct.
[Document](https://sideci.com/ja/docs/autofix-rubocop)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-04 09:28 UTC, tomoyuki-tanaka commented on app/controllers/monthly_reports_controller.rb
> +    @monthly_reports = @monthly_reports.where(target_month: search_params[:target_month].to_date) if search_params.try(:[],:target_month).present?
search_params.try~についてはメソッドにして分かりやすい名前をつけた方がいいかと思います。
それから再代入しないようにできないですかね

2017-02-04 10:23 UTC, masahiro-yamazaki commented on app/controllers/monthly_reports_controller.rb
> +    @monthly_reports = @monthly_reports.where(target_month: search_params[:target_month].to_date) if search_params.try(:[],:target_month).present?
コメントありがとうございます！
「レビューにあたって」にも書いたんですが、
Ransackで日付型の検索ができれば、再代入せずによくなると思います。

2017-02-04 12:10 UTC, tomoyuki-tanaka commented on app/controllers/monthly_reports_controller.rb
> +    @monthly_reports = @monthly_reports.where(target_month: search_params[:target_month].to_date) if search_params.try(:[],:target_month).present?
なるほどですー 👍

2017-02-04 12:30 UTC, tomoyuki-tanaka commented on app/models/monthly_report.rb
> +    first_month, last_month = target_months.first, target_months.last
`target_month.map { |month| month.strftime('%Y年%m月') }` で一行でいけると思いますー :octocat:

2017-02-04 12:34 UTC, t-tonchim approved these changes

2017-02-04 13:22 UTC, freezer530000 commented on app/controllers/monthly_reports_controller.rb
> +  def index
__[rubocop]__
* Carriage return character detected. [:ref](https://github.com/bbatsov/ruby-style-guide#crlf)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-04 13:22 UTC, freezer530000 commented
Click here if you want to create rubocop's auto-correct Pull Request
[![Auto Correct by SideCI](https://sideci.com/autofix.png)](https://sideci.com/gh/42654368/issues/pull_request/428/diff/30fa9801bd4ca4188544a3c7051cfaffc618e0f2?open_modal=1#rubocop)

See the documentation if you want to get more information about auto-correct.
[Document](https://sideci.com/ja/docs/autofix-rubocop)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-04 23:45 UTC, bakunyo commented
README にも書いてますが、Pushする前に `rubocop` しましょう 👍

2017-02-04 23:48 UTC, bakunyo commented
Ransack の拡張しなくても、デフォルトで検索ができる状態になっていると思います。
```
irb(main):015:0> MonthlyReport.search(target_month_eq: '20170101').result
  MonthlyReport Load (0.4ms)  SELECT "monthly_reports".* FROM "monthly_reports" WHERE "monthly_reports"."target_month" = '2017-01-01'
```
↑ `develop` ブランチでの実行結果

2017-02-04 23:53 UTC, bakunyo commented on app/models/monthly_report.rb
> +  end
ちょっと冗長なので、
```
min = MonthlyReport.released.minimum(:target_month)
max = MonthlyReport.released.maximum(:target_month)
(min..max).map { |d| [d.strftime({ゴニョゴニョ}), d.strftime({ゴニョゴニョ})] }
```
とかでどうでしょう。SQL2回になりますが、月報が積み上がる度に `uniq` 前の配列が膨れ上がっていくので…

2017-02-05 14:13 UTC, masahiro-yamazaki commented
bundle exec rubocop
を実行したところ、以下の結果になりました。
どう対処すればいいか分からないのですが、どなたかご存知でしょうか？

[root@localhost hr-dash]# bundle exec rubocop
Inspecting 123 files
......................C....................................................................................................

Offenses:

app/controllers/monthly_reports_controller.rb:1:1: C: Class has too many lines. [118/100]
class MonthlyReportsController < ApplicationController
^^^^^
app/controllers/monthly_reports_controller.rb:24:3: C: Method has too many lines. [12/10]
  def create
  ^^^
app/controllers/monthly_reports_controller.rb:43:3: C: Method has too many lines. [11/10]
  def update
  ^^^

123 files inspected, 3 offenses detected

2017-02-05 14:24 UTC, masahiro-yamazaki commented
@bakunyo 
レビューありがとうございます。
Ransack の拡張をしなくてもDate型検索できる、というのは知らなかったので助かりました！

target_monthsの配列からmapを使って[ラベル、target_month]の配列を作成すればシンプルになりますね...。
target_monthsを取得する箇所で、(min..max)だとすべての日付(例えば11/1,11/2,11/3,...)が表示されます。
今回は月初の日付のみ表示させたかったので、selectを使って、day == day.beginning_of_monthとなる
日付だけを配列として取得しました。

2017-02-06 15:20 UTC, bakunyo commented
@masahiro-yamazaki 
> target_monthsを取得する箇所で、(min..max)だとすべての日付(例えば11/1,11/2,11/3,...)が表示されます。

すみません、これすっかり抜け落ちてたので、`min..max` 無理に使わなくて良いです 💦 
`day.next_month` とかで適切な日だけ取得してもらえればと思います。

2017-02-18 15:52 UTC, masahiro-yamazaki commented on app/controllers/monthly_reports_controller.rb
>        :target_month,
:target_month,
を削除してしまうと月報新規作成時に
「対象月を指定してください」のエラーが出るので
target_monthは削除しませんでした。

2017-02-18 22:28 UTC, tomoyuki-tanaka commented
あ、あとテストもー！以前検索のテスト書いたので参考にしてもらえば良いかと

2017-02-20 11:59 UTC, t-tonchim commented on app/controllers/monthly_reports_controller.rb
> +      :target_month_eq,
これ必要ですか？検索時にはsearch_paramsしか使ってないような気がするんですが

2017-02-21 14:06 UTC, t-tonchim requested changes
指摘しましたー

2017-02-21 14:06 UTC, t-tonchim commented on spec/features/monthly_report_spec.rb
> +        let(:report2) { create(:monthly_report, :shipped, user: user1, tags: [tag], target_month: month2) }
tagとuserを指定する必要って特にありますか ❓

2017-02-21 14:06 UTC, t-tonchim commented on spec/features/monthly_report_spec.rb
> +        month2 = 2.months.ago.beginning_of_month
letじゃないのってなぜですか ❓

2017-02-21 14:06 UTC, tomoyuki-tanaka commented on spec/features/monthly_report_spec.rb
> +          report2.save
createしているのでsaveする必要はないのでは ❓   before内でDBの値を参照する場合は `let!` を使えば解決すると思います。

2017-02-21 14:06 UTC, tomoyuki-tanaka commented on spec/features/monthly_report_spec.rb
> +          find('#monthly_report_tags_input').set(tag.name)
今回はタグ関係ないのでいらないかと

2017-02-21 16:19 UTC, masahiro-yamazaki commented on spec/features/monthly_report_spec.rb
> +        let(:report2) { create(:monthly_report, :shipped, user: user1, tags: [tag], target_month: month2) }
レビューありがとうございます！
月報作成時に、タグがない場合は
「ActiveRecord::RecordInvalid:
   バリデーションに失敗しました 使用した技術を入力してください」
のバリデートが実行され、データが作成されないので、タグを追加しました。

2017-02-21 22:40 UTC, tomoyuki-tanaka commented on spec/features/monthly_report_spec.rb
> +        let(:report2) { create(:monthly_report, :shipped, user: user1, tags: [tag], target_month: month2) }
なるほど。そういうことでしたら `:with_tags` を指定すればいいですよー。そうすればletで生成する必要もないです。

2017-02-24 13:19 UTC, tomoyuki-tanaka commented on spec/features/monthly_report_spec.rb
> +          select "#{report1.target_month.strftime('%Y年%m月')}", from: 'q[target_month_eq]'
`report1.target_month.strftime('%Y年%m月')` の結果は文字列なので式展開しなくて良さそうな気がするんですがどうでしょう ❓

2017-02-24 13:49 UTC, tomoyuki-tanaka commented
あと細々したコミットが多くなってきたので程よい単位で[squash](https://iwb.jp/git-commit-rebase-squash/)してもらえたら良いかと思いますー

2017-02-25 14:21 UTC, masahiro-yamazaki commented on spec/features/monthly_report_spec.rb
> +          select "#{report1.target_month.strftime('%Y年%m月')}", from: 'q[target_month_eq]'
"#{}"は使わなくて大丈夫ですね。修正しました！

2017-02-25 14:23 UTC, masahiro-yamazaki commented
@tomoyuki-tanaka 
squashする場合、別のブランチを切ってpushした方がいいですか？
(今のブランチにgit push -f するのはよくないと思うので)
https://iwb.jp/git-commit-rebase-squash/

2017-02-25 15:40 UTC, tomoyuki-tanaka commented
自分のブランチなのでpush -f していいと思いますよ、他の人に影響は出ないので。developとかにpush -fするのはまずいですけど

2017-02-26 00:53 UTC, tomoyuki-tanaka commented
> すみません、これすっかり抜け落ちてたので、min..max 無理に使わなくて良いです 💦
> day.next_month とかで適切な日だけ取得してもらえればと思います。
あとはこれだけですねー

2017-02-26 04:39 UTC, tomoyuki-tanaka commented on app/models/monthly_report.rb
> +  end
月初の配列を取得するという責任を別のメソッドにしてもいいかもしれませんね
```ruby
def 気の利いたメソッド名(first_month, last_month)
  loop.each_with_object([first_month]) do |_, days|
    nm = days.last.next_month
    nm > last_month ? (break days) : days << nm
  end
end
```

2017-02-26 04:56 UTC, tomoyuki-tanaka commented on app/models/monthly_report.rb
> +    options
月初の配列を取得するという責任を別のメソッドにしてもいいかもしれませんね
```ruby
def 気の利いたメソッド名(first_month, last_month)
  loop.each_with_object([first_month]) do |_, days|
    nm = days.last.next_month
    nm > last_month ? (break days) : days << nm
  end
end
```

2017-02-27 14:42 UTC, freezer530000 commented on app/models/monthly_report.rb
> +    all_months(first_month, last_month).map{ |month| [month.strftime('%Y年%m月'), month] }
__[rubocop]__
* Space missing to the left of {.

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-27 14:42 UTC, freezer530000 commented
Click here if you want to create rubocop's auto-correct Pull Request
[![Auto Correct by SideCI](https://sideci.com/autofix.png)](https://sideci.com/gh/42654368/issues/pull_request/428/diff/f15fa48898ab41305bb9f8fd0687ee3db836ce73?open_modal=1#rubocop)

See the documentation if you want to get more information about auto-correct.
[Document](https://sideci.com/ja/docs/autofix-rubocop)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-02-28 12:53 UTC, tomoyuki-tanaka commented on app/models/monthly_report.rb
> +  end
あ、後出しでいろいろ言って申し訳ないんですが、今回モデルに追加した二つのクラスメソッドのテストもお願いします。

2017-02-28 16:21 UTC, masahiro-yamazaki commented on app/models/monthly_report.rb
> +  end
了解です！

2017-03-01 22:57 UTC, tomoyuki-tanaka commented on spec/models/monthly_report_spec.rb
> +  describe 'target_month_select_options' do
細かいですが、クラスメソッドは `#method_name` みたいな感じで `.method_name` って書くんですよ

2017-03-05 04:30 UTC, t-tonchim approved these changes
LGTM

2017-03-05 04:45 UTC, freezer530000 commented on app/models/monthly_report.rb
> +    return [] if MonthlyReport.released.blank?
__[reek]__
* [DuplicateMethodCall] calls MonthlyReport.released 3 times [:ref](https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-03-05 04:45 UTC, freezer530000 commented on app/models/monthly_report.rb
> +    first_month = MonthlyReport.released.minimum(:target_month)
__[reek]__
* [DuplicateMethodCall] calls MonthlyReport.released 3 times [:ref](https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-03-05 04:45 UTC, freezer530000 commented on app/models/monthly_report.rb
> +    last_month = MonthlyReport.released.maximum(:target_month)
__[reek]__
* [DuplicateMethodCall] calls MonthlyReport.released 3 times [:ref](https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md)

<!-- Comment by [SideCI](https://sideci.com) -->

2017-03-09 12:50 UTC, bakunyo commented
![image](https://cloud.githubusercontent.com/assets/2487437/23750898/5b3a0de4-0512-11e7-92da-fd29dd29be75.png)

2017-03-09 12:53 UTC, merged